backend:
  name: github # Changed from git-gateway
  repo: Y24KL/mediablastnetworkweb
  branch: main
  base_url: https://mediablastnetworkweb.vercel.app/

media_folder: "image"
public_folder: "image"

collections:
  - name: "settings"
    label: "Site Settings"
    delete: false
    editor:
      preview: false
    files:
      - file: "settings.json"
        label: "Stream Configuration"
        name: "stream_config"
        fields:
          - {label: "Stream URL", name: "stream_url", widget: "string"}
          - {label: "Is Live Now?", name: "is_live", widget: "boolean", default: false}
          - {label: "Backup Video URL", name: "backup_url", widget: "string"}
          - {label: "Stream Title", name: "stream_title", widget: "string", default: "Mediablasst Exclusive Feed"}
