backend:
  name: github
  repo: Y24KL/mediablastnetworkweb
  branch: main # Or your default branch name
  base_url: https://netlify-cms-github-oauth-provider-1piz.onrender.com

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
